Iter13
MaximMNsk/go-url-shortener pull request #13
Opened 2023-10-21 07:30 UTC by MaximMNsk

2023-10-24 15:12 UTC, kilchik requested changes

2023-10-24 15:12 UTC, kilchik commented on internal/models/database/row.go
> +func saveData(data JSONData) (JSONData, error) {
Зачем функция возвращает свой аргумент?

2023-10-24 15:12 UTC, kilchik commented on internal/models/database/row.go
> +	var err error
Зачем нужно отдельное объявление переменной?

2023-10-24 15:12 UTC, kilchik commented on internal/models/memory/structs.go
> +var storage []JSONData
Почему storage - slice, а не map?
Глобальных переменных быть не должно.
Глобальные объекты чреваты
* огромными затруднениями при написании тестов
* сложноотловимыми багами, связанными с рейсами (тут storage непотокобезопасен, вижу обращения к нему из разных горутин)
* сложноотловимыми багами в целом, потому что к объекту есть доступ из любого куска кода, очень сложно локализовать изменение, приведшее к багу

2023-10-24 15:12 UTC, kilchik commented on internal/models/database/row.go
> +	connection := db.GetDB()
DB - такой же сторадж, как и map/slice. Тут напрашивается полиморфизм. Хранилище должно представлять из себя интерфейс, конкретная имплементация которого зависит от конфигурационных параметров. Другими словами, тебе нужно сделать структуру MemStorage (с методами над map/slice) и DBStorage (с теми же методами над БД), а также интерфейс Storage. При инициализации в main (без глобальных переменных) в зависимости от параметров конфигурации создается объект одной из двух структур, в другие пакеты же этот объект должен пробрасываться как интерфейс Storage.

2023-10-24 15:12 UTC, kilchik commented on cmd/shortener/main.go
> +	if storage == "database" {
Здесь копипаст, от ифов нужно избавиться с помощью полиморфизма хранилища, реализованного на интерфейсе - подробности в комментарии ниже

2023-10-26 14:03 UTC, MaximMNsk commented
У меня общий коммент.
Проектировать нужно да, на уровне абстракций. Переделал инициализацию storage таким способом. Он, действительно, правильнее. Код получился намного чище.
Мьютексы поправил.
Для памяти storage сделал как глобальную переменную потому, что в реальной жизни мало кто хранит неиндексные данные в памяти. Самый небезопасный и некрасивый способ. Можно, конечно, сделать объект со своими геттерами и сеттерами и обращаться к нему, но для работоспособной простоты, имхо, этого хватит. Если действительно нужно и пригодится в будущем - я переделаю, только скажи.
Про возвращаемые методами значения в параметр - тоже переделал. 
И по логике у меня был вопрос. Насколько корректна текущая реализация?
У меня сейчас работает так. Приходит урл. От него генерится хэш, который есть его идентификатор. Все происходит в хэндлере. Дальше, хэндлер отправляет модель в storage, где все сохраняется. После этого хэндлер смотрит на ошибки и отдает ответ, который был по сути просчитан в самом начале.
Плюсы. Сохраняется уникальность пары ИД -> урл, нет необходимости проверять уникальность в storage. Запрос к storage только один. 
Когда реализовывал без хэша и просто генерил рандомный идентификатор, столкнулся с тем, что запросов к storage минимум два (для проверки уникальности). А если придерживаться "правильной" логики, то можно реализовать и в три запроса - проверка на уникальность, сохранение, чтение сохраненного для вывода ответа. )) Но здесь есть плюс. Если нужно разным пользователям делать разные шортлинки от одного урла, то этот вариант предпочтительнее (только как этим будут пользоваться в реальной жизни?). 
Отсюда тоже вопрос. Будет ли дальше необходимость этого разделения?

2023-10-28 08:38 UTC, kilchik requested changes
- Нужно поправить работу с контекстами в БД
- initStorage должна вызываться один раз при старте приложения, а не в каждом хендлере

> Для памяти storage сделал как глобальную переменную потому, что в реальной жизни мало кто хранит неиндексные данные в памяти. Самый небезопасный и некрасивый способ. Можно, конечно, сделать объект со своими геттерами и сеттерами и обращаться к нему, но для работоспособной простоты, имхо, этого хватит. Если действительно нужно и пригодится в будущем - я переделаю, только скажи.

В реальной жизни многие данные хранятся в памяти, например, кэш. Боюсь, работоспособной простоты не получилось, пч глобальная переменная тут никак не защищена от конкурентного доступа. Совершенно точно стоит сделать структуру с сеттером и геттером, которые будут инкапсулировать в себе защиту от конкурентного доступа

> У меня сейчас работает так. Приходит урл. От него генерится хэш, который есть его идентификатор. Все происходит в хэндлере. Дальше, хэндлер отправляет модель в storage, где все сохраняется. После этого хэндлер смотрит на ошибки и отдает ответ, который был по сути просчитан в самом начале.
Плюсы. Сохраняется уникальность пары ИД -> урл, нет необходимости проверять уникальность в storage. Запрос к storage только один.

Это ок, только вот такого `if strings.Contains(err.Error(), `SQLSTATE 23505`)` на уровне хэндлера быть не должно - нужно возвращать типизированную ошибку из слоя хранилища

2023-10-28 08:38 UTC, kilchik commented on internal/models/database/row.go
> +	_, err := connect.Exec(db.GetCtx(), createSchemaQuery)
Context должен пробрасываться из хэндлера - это не должен быть один общий контекст для всех запросов.
В противном случае велика вероятность, что при временном подвисании запросов к БД клиентские соединения будут каскадно завершаться по таймауту, а соединения с БД будут продолжать висеть, пока новые клиентские соединения не приведут к достижению лимита по установленным соединениям

2023-10-31 15:21 UTC, merged