Iter5
MaximMNsk/go-url-shortener pull request #5
Opened 2023-09-16 12:21 UTC by MaximMNsk

2023-09-19 20:08 UTC, kilchik requested changes

2023-09-19 20:08 UTC, kilchik commented on cmd/shortener/main.go
> +	if errBody == nil {
Лучше понижать цикломатическую сложность функции, используя быстрый выход:
```
if errBody != nil {
  // log error
  BadRequest(err)
  return
}
// alternative branch
```

2023-09-19 20:08 UTC, kilchik commented on cmd/shortener/main.go
> +func handlePOST(res http.ResponseWriter, req *http.Request) {
Советую вынести хэндлеры в промежуточный слой (пакет) server/app, который будет инкапсулировать в себе обработку запросов и формирование ответов

2023-09-19 20:08 UTC, kilchik commented on internal/models/files/json.go
> +	f, _ := os.OpenFile(fileName, os.O_RDONLY, 0644)
Никогда не игнорируем ошибки

2023-09-19 20:08 UTC, kilchik commented on internal/models/files/json.go
> +			panic(err)
Здесь паника приведет к тому, что один-единственный запрос, приведший к ошибке, свалит все приложение. Наша задача - не в том, чтобы работал хороший сценарий (это само собой), но в том, чтобы при исключительных ситуациях сервер деградировал настолько слабо, насколько это возможно

2023-09-19 20:08 UTC, kilchik commented on internal/models/files/json.go
> +	content, _ := json.Marshal(toSave)
Нельзя игнорировать ошибки

2023-09-23 09:55 UTC, kilchik approved these changes

2023-09-23 09:55 UTC, kilchik commented on cmd/shortener/main.go
> +	logger.PrintLog("INFO", "Start server")
INFO и другие уровни логирования нужно вынести в константы

2023-09-23 10:57 UTC, MaximMNsk commented on cmd/shortener/main.go
> +	logger.PrintLog("INFO", "Start server")
Кстати, да. Сделано.

2023-09-23 11:00 UTC, merged